version: '3.8'
services:
  zomboid-rcon:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RCON_HOST=${RCON_HOST}
      - RCON_PORT=${RCON_PORT}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    # Optionally mount code for live edit
    # volumes:
    #   - ./:/app